Build and publish Docker images
blue-nebula/base pull request #257
Opened 2023-04-13 00:27 UTC by TheAssassin

See https://github.com/TheAssassin/base/pkgs/container/bn-server for a demo. The images are fully working and optimized for size.

For now, we will only have a moving target tag called `master` (and possibly others for other branches) for public use. Once we create a tag, we'll have a similarly named tag pushed to the registry as well.

The `Dockerfile` and the docker-compose config were written from scratch. The remaining scripting comes from https://github.com/TheAssassin/redeclipse-docker/.

Note that we do not have any documentation on how to use these. We should document how you can dump the `servinit.cfg` template so as a user, you can see which variables are available.

2023-04-15 18:08 UTC, voidanix requested changes
Just a few nits (and questions), otherwise looks good.

2023-04-17 15:56 UTC, TheAssassin commented on .github/workflows/docker.yml
> +          #platforms: linux/amd64,linux/arm64
We could add a special build that builds arm64 container images on demand (e.g., using the `workflow_dispatch` trigger).

An alternative would be to rent some arm64 VPS ("cloud instance") and host our own runner, but I don't think that is viable at this point.

2023-04-20 21:55 UTC, TheAssassin commented on docker/Dockerfile
> +RUN apk add gcc g++ binutils sdl2-dev zlib-dev perl git wget ca-certificates coreutils mesa-dev musl-dev glu-dev \
`--no-cache` is not needed any more. `apk` used to require a separate `apk update` or `--no-cache` to fetch information on the repositories before `apk install`. I'll fix the other location.

2023-04-20 21:57 UTC, TheAssassin commented on docker/Dockerfile
> +MAINTAINER "TheAssassin <theassassin@assassinate-you.net>"
Let's just dump it altogether.

2023-04-20 21:57 UTC, TheAssassin commented on docker/Dockerfile
> +    ls -al && \
It's good for debugging. It won't cost any runtime.

2023-04-20 21:58 UTC, TheAssassin commented on docker/serverip.patch
The patch fixes behavior with a masterserver on the same host. Without this patch, the servers will not be listed publicly, as the master server only sees the local IP (unless one uses some unsafe options like `--net=host`). I'd love to get rid of it, though.

2023-04-23 00:04 UTC, voidanix commented on .github/workflows/docker.yml
> +          #platforms: linux/amd64,linux/arm64
The first option sounds good, would you like to do this in the current PR?

2023-04-23 00:04 UTC, TheAssassin commented on .github/workflows/docker.yml
> +          #platforms: linux/amd64,linux/arm64
Can do that.

2023-04-23 00:05 UTC, voidanix commented on docker/Dockerfile
> +MAINTAINER "TheAssassin <theassassin@assassinate-you.net>"
Fine by me, you can also use `LABEL maintainer="Blue Nebula Team"` or similar just in case.

2023-04-23 00:05 UTC, voidanix commented on docker/serverip.patch
I see, thanks for covering this!

2023-04-24 00:12 UTC, TheAssassin commented on .github/workflows/docker.yml
> +          #platforms: linux/amd64,linux/arm64
Done, as [demo'd in my fork](https://github.com/TheAssassin/base/actions/runs/4781130285/jobs/8499305368).

2023-04-28 00:47 UTC, TheAssassin commented
I managed to remove the patch by introducing a new server variable called `serverpublicip`, which allows a server to advertise itself to a masterserver properly if both are in the same subnet or on the same host. The masterserver already knows it should use the advertised one. As the master will ping the server anyway using either the advertised IP or the one found in the UDP packet, this should work just fine (just like it used to in the last years with the old workaround that abused `serverip` for the purpose).

2023-04-28 21:04 UTC, TheAssassin commented
Tested this new variable in production now, works just the way it's meant to work.

2023-04-28 21:21 UTC, voidanix commented on src/engine/server.cpp
> +    };
Useless semicolon here.

2023-04-28 21:21 UTC, voidanix commented on src/engine/server.cpp
> +    if(setupserversockets() && verbose) {
Style:
```suggestion
    if (setupserversockets() && verbose) {
```

2023-04-28 21:21 UTC, voidanix commented on src/game/auth.h
> +            char* advertisedIp;
Style again: specify the pointer with `char* advertisedIp;` to make it consistent with the code below.

2023-04-28 21:21 UTC, voidanix commented on src/game/auth.h
> +                advertisedIp = "*";
```
bn/src/game/auth.h:447:32: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  447 |                 advertisedIp = "*";
      |                                ^~~
```

Consider `const`-ifying

2023-04-28 21:21 UTC, voidanix commented on .gitignore
> +!docker/serverip.patch
You can remove this now as it does not exist anymore.

2025-06-10 21:09 UTC, TheAssassin commented
Closing in favor of #272.

2025-06-10 21:09 UTC, closed without merging